=== arthurfiddich/rise-app/trunk/com.data.generator.xmlns/xsd/data-generator-gplace-api.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://xmlns.data.generator.com/gplace/api/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.data.generator.com/gplace/api/v1">

    <xsd:complexType name="PlaceDetailsResponse">
    	<xsd:sequence>
            <xsd:element name="status" type="xsd:token" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="result" type="tns:Result" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:element name="placeDetailsResponse" type="tns:PlaceDetailsResponse">
    </xsd:element>

    <xsd:complexType name="Result">
    	<xsd:sequence>
    		<xsd:element name="addressComponent" type="tns:AddressComponent" maxOccurs="unbounded" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="name" type="xsd:token" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="vicinity" type="xsd:token" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="type" type="xsd:token" maxOccurs="unbounded" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="formattedPhoneNumber" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="formattedAddress" type="xsd:token" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="event" type="tns:Event" maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="geometry" type="tns:Geometry" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="url" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="icon" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="reference" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="id" type="xsd:token" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="internationalPhoneNumber" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="website" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="review" type="tns:Review" maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="openingHours" type="tns:OpeningHours" maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="utcOffset" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="photo" type="tns:Photo" maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="priceLevel" type="xsd:int" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="rating" type="xsd:double" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="adrAddress" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="userRatingsTotal" type="xsd:int" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AddressComponent">
    	<xsd:sequence>
    		<xsd:element name="type" type="xsd:token" maxOccurs="unbounded" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="longName" type="xsd:token" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="shortName" type="xsd:token" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Event">
    	<xsd:sequence>
    		<xsd:element name="eventId" type="xsd:token" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="startTime" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="summary" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="url" type="xsd:token" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Geometry">
    	<xsd:sequence>
    		<xsd:element name="location" type="tns:Location" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Location">
    	<xsd:sequence>
    		<xsd:element name="lat" type="xsd:double" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="lng" type="xsd:double" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Review">
    	<xsd:sequence>
    		<xsd:element name="aspect" type="tns:Aspect" maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="authorName" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="authorUrl" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="language" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="rating" type="xsd:double" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="text" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="time" type="xsd:token" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Aspect">
    	<xsd:sequence>
    		<xsd:element name="type" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="rating" type="xsd:double" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="OpeningHours">
    	<xsd:sequence>
    		<xsd:element name="openNow" type="xsd:boolean" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="period" type="tns:Period" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Period">
    	<xsd:sequence>
    		<xsd:element name="open" type="tns:Open" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="close" type="tns:Close" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Open">
    	<xsd:sequence>
    		<xsd:element name="day" type="xsd:int" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="time" type="xsd:token" maxOccurs="1" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Close">
    	<xsd:sequence>
    		<xsd:element name="day" type="xsd:int" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="time" type="xsd:token" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Photo">
    	<xsd:sequence>
    		<xsd:element name="photoReference" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="height" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="width" type="xsd:token" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="htmlAttribution" type="xsd:token" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== arthurfiddich/rise-app/trunk/com.data.generator.xmlns/xsd/data-generator-gplace-api.xml
<?xml version="1.0" encoding="UTF-8"?>
<placeDetailsResponse xmlns="http://xmlns.data.generator.com/gplace/api/v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.data.generator.com/gplace/api/v1 data-generator-gplace-api.xsd ">
	<status>token</status>
	<result>
		<addressComponent>
			<type>token</type>
			<longName>token</longName>
			<shortName>token</shortName>
		</addressComponent>
		<name>token</name>
		<vicinity>token</vicinity>
		<type>token</type>
		<formattedPhoneNumber>token</formattedPhoneNumber>
		<formattedAddress>token</formattedAddress>
		<event>
			<eventId>token</eventId>
			<startTime>token</startTime>
			<summary>token</summary>
			<url>token</url>
		</event>
		<geometry>
			<location>
				<lat>0.0</lat>
				<lng>0.0</lng>
			</location>
		</geometry>
		<url>token</url>
		<icon>token</icon>
		<reference>token</reference>
		<id>token</id>
		<internationalPhoneNumber>token</internationalPhoneNumber>
		<website>token</website>
		<review>
			<aspect>
				<type>token</type>
				<rating>0.0</rating>
			</aspect>
			<authorName>token</authorName>
			<authorUrl>token</authorUrl>
			<language>token</language>
			<rating>0.0</rating>
			<text>token</text>
			<time>token</time>
		</review>
		<openingHours>
			<openNow>true</openNow>
			<period>
				<open>
					<day>0</day>
					<time>token</time>
				</open>
				<close>
					<day>0</day>
					<time>token</time>
				</close>
			</period>
		</openingHours>
		<utcOffset>token</utcOffset>
		<photo>
			<photoReference>token</photoReference>
			<height>token</height>
			<width>token</width>
			<htmlAttribution>token</htmlAttribution>
		</photo>
		<priceLevel>0</priceLevel>
		<rating>0.0</rating>
		<adrAddress>token</adrAddress>
		<userRatingsTotal>0</userRatingsTotal>
	</result>
</placeDetailsResponse>
