=== arthurfiddich/rise-app/trunk/com.data.generator.xmlns/xsd/data-generator-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://xmlns.data.generator.com/configuration/v1" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.data.generator.com/configuration/v1">

    <element name="dataSourceConfiguration"
    	type="tns:DataSourceConfiguration">
    </element>
    
    <complexType name="DataSourceConfiguration">
    	<complexContent>
    		<extension base="tns:BaseObject">
    			<sequence>
    				<element name="mainDataSource" type="tns:DataSource"
    					maxOccurs="1" minOccurs="1">
    				</element>
    				<element name="additionalDataSource" type="tns:AdditionalDataSource"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="DataSource">
    	<sequence>
    		<element name="name" type="token" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="entity" type="tns:Entity" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="BaseObject">
    	<sequence>
    		<element name="id" type="ID" maxOccurs="1" minOccurs="1"></element>
    		<element name="uniqueId" type="token" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="dateGenerated" type="dateTime" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="lastModified" type="dateTime" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="dateCreated" type="dateTime" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="AdditionalDataSource">
    	<sequence>
    		<element name="name" type="token" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="Entity">
    	<complexContent>
    		<extension base="tns:BaseObject">
    			<sequence>
    				<element name="name" type="token" maxOccurs="1"
    					minOccurs="1">
    				</element>
    				<element name="label" type="token" maxOccurs="1"
    					minOccurs="1">
    				</element>
    				<element name="field" type="tns:Field"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Field">
    	<complexContent>
    		<extension base="tns:BaseObject">
    			<sequence>
    				<element name="name" type="token" maxOccurs="1"
    					minOccurs="1">
    				</element>
    				<element name="label" type="token" maxOccurs="1"
    					minOccurs="1">
    				</element>
    				<element name="type" type="token" maxOccurs="1"
    					minOccurs="1">
    				</element>
    				<element name="length" type="double" maxOccurs="1"
    					minOccurs="0">
    				</element>
    				<element name="maxLength" type="double"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="precision" type="unsignedInt"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="scale" type="unsignedInt"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="digits" type="double" maxOccurs="1"
    					minOccurs="0">
    				</element>
    				<element name="byteLength" type="double"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="calculatedFormula" type="token"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="controllerName" type="token"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="defaultValue" type="token"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="soapType" type="token" maxOccurs="1"
    					minOccurs="0">
    				</element>
    				<element name="unique" type="boolean" maxOccurs="1"
    					minOccurs="0">
    				</element>
    				<element name="nameField" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="nullable" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="custom" type="boolean" maxOccurs="1"
    					minOccurs="0">
    				</element>
    				<element name="updatable" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="filterable" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="autoNumber" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="idLookup" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="externalId" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="htmlFormatted" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="computedValue" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="caseSensitive" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="namePointing" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="pickList" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="restrictedPickList" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="sortable" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="groupable" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="inlineHelpText" type="token"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="relationshipOrder" type="double"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="calculated" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="createable" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="hasDependentPickLists" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="usedInReports" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="usedInCharts" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="writeRequiresMasterRead"
    					type="boolean" maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="defaultedOnCreate" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="deprecatedAndHidden" type="boolean"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="relationship" type="token"
    					maxOccurs="1" minOccurs="0">
    				</element>
    				<element name="enitityUniqueId" type="token"
    					maxOccurs="1" minOccurs="1">
    				</element>
    				<element name="referenceTo" type="token"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    				<element name="entity" type="tns:ObjectRef"
    					maxOccurs="1" minOccurs="1">
    				</element>
    				<element name="picklistItems"
    					type="tns:PicklistItem" maxOccurs="unbounded" minOccurs="0">
    				</element>
    				<element name="dataSourceFieldName" type="tns:DataSourceFieldName" maxOccurs="1" minOccurs="0"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ObjectRef">
    	<sequence>
    		<element name="refId" type="IDREF" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="PicklistItem">
    	<sequence>
    		<element name="dataSource" type="token" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="active" type="boolean" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="defaultValue" type="boolean" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="label" type="token" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="validFor" type="byte" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="value" type="token" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="DataSourceFieldName">
    	<sequence>
            <element name="fieldName" type="token" maxOccurs="1" minOccurs="1"></element>
            <element name="fieldType" type="token" maxOccurs="1"
    			minOccurs="1">
    		</element>
        </sequence>
    </complexType>
</schema>

=== arthurfiddich/rise-app/com.data.generator.xmlns/xsd/data-generator-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataSourceConfiguration
	xmlns="http://xmlns.data.generator.com/configuration/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.data.generator.com/configuration/v1 data-generator-configuration.xsd ">
	<id>idvalue0</id>
	<uniqueId>token</uniqueId>
	<dateGenerated>2001-12-31T12:00:00</dateGenerated>
	<lastModified>2001-12-31T12:00:00</lastModified>
	<dateCreated>2001-12-31T12:00:00</dateCreated>
	<mainDataSource>
		<name>token</name>
		<entity>
			<id>idvalue1</id>
			<uniqueId>token</uniqueId>
			<dateGenerated>2001-12-31T12:00:00</dateGenerated>
			<lastModified>2001-12-31T12:00:00</lastModified>
			<dateCreated>2001-12-31T12:00:00</dateCreated>
			<name>token</name>
			<label>token</label>
			<field>
				<id>idvalue2</id>
				<uniqueId>token</uniqueId>
				<dateGenerated>2001-12-31T12:00:00</dateGenerated>
				<lastModified>2001-12-31T12:00:00</lastModified>
				<dateCreated>2001-12-31T12:00:00</dateCreated>
				<name>token</name>
				<label>token</label>
				<type>token</type>
				<length>0.0</length>
				<maxLength>0.0</maxLength>
				<precision>0</precision>
				<scale>0</scale>
				<digits>0.0</digits>
				<byteLength>0.0</byteLength>
				<calculatedFormula>token</calculatedFormula>
				<controllerName>token</controllerName>
				<defaultValue>token</defaultValue>
				<soapType>token</soapType>
				<unique>true</unique>
				<nameField>true</nameField>
				<nullable>true</nullable>
				<custom>true</custom>
				<updatable>true</updatable>
				<filterable>true</filterable>
				<autoNumber>true</autoNumber>
				<idLookup>true</idLookup>
				<externalId>true</externalId>
				<htmlFormatted>true</htmlFormatted>
				<computedValue>true</computedValue>
				<caseSensitive>true</caseSensitive>
				<namePointing>true</namePointing>
				<pickList>true</pickList>
				<restrictedPickList>true</restrictedPickList>
				<sortable>true</sortable>
				<groupable>true</groupable>
				<inlineHelpText>token</inlineHelpText>
				<relationshipOrder>0.0</relationshipOrder>
				<calculated>true</calculated>
				<createable>true</createable>
				<hasDependentPickLists>true</hasDependentPickLists>
				<usedInReports>true</usedInReports>
				<usedInCharts>true</usedInCharts>
				<writeRequiresMasterRead>true</writeRequiresMasterRead>
				<defaultedOnCreate>true</defaultedOnCreate>
				<deprecatedAndHidden>true</deprecatedAndHidden>
				<relationship>token</relationship>
				<enitityUniqueId>token</enitityUniqueId>
				<referenceTo>token</referenceTo>
				<entity>
					<refId>idvalue0</refId>
				</entity>
				<picklistItems>
					<dataSource>token</dataSource>
					<active>true</active>
					<defaultValue>true</defaultValue>
					<label>token</label>
					<validFor>0</validFor>
					<value>token</value>
				</picklistItems>
				<dataSourceFieldName>
					<fieldName>token</fieldName>
					<fieldType>token</fieldType>
				</dataSourceFieldName>
			</field>
		</entity>
	</mainDataSource>
	<additionalDataSource>
		<name>token</name>
	</additionalDataSource>
</dataSourceConfiguration>
