=== arthurfiddich/rise-app/trunk/com.rise.xmlns/xsd/com.rise.query.config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://xmlns.rise.com/common/v1" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://xmlns.rise.com/common/v1">


    <xsd:element name="queryConfigs" type="QueryConfigs"></xsd:element>
    
    <xsd:complexType name="QueryConfigs">
    	<xsd:sequence>
    		<xsd:element name="queryConfig" type="QueryConfig" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="QueryConfig">
    	<xsd:sequence>
    		<xsd:element name="className" type="Token" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="component" type="Component"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="superClass" type="SuperClass"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="field" type="Field" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:simpleType name="Token">
    	<xsd:restriction base="xsd:token">
    		<xsd:minLength value="1"></xsd:minLength>
    		<xsd:whiteSpace value="collapse"></xsd:whiteSpace>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Component">
    	<xsd:sequence>
    		<xsd:element name="name" type="Token" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="SuperClass">
    	<xsd:sequence>
    		<xsd:element name="name" type="Token" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Field">
    	<xsd:sequence>
    		<xsd:element name="name" type="Token" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="type" type="Token" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== arthurfiddich/rise-app/trunk/com.rise.daemon/conf/com.rise.query.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryConfigs xmlns="http://xmlns.rise.com/common/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.rise.com/common/v1 ../../com.rise.xmlns/xsd/com.rise.query.config.xsd ">
  <queryConfig>
    <className>com.rise.common.model.Person</className>
    <component>
      <name>educationQualifications</name>
      <name>employmentExperiences</name>
      <name>contactInformation</name>
      <name>driversLicense</name>
      <name>personName</name>
      <name>candidate</name>
      <name>passport</name>
      <name>awards</name>
    </component>
    <superClass>
      <name>baseModel</name>
    </superClass>
    <field>
      <name>id</name>
      <type>java.lang.Integer</type>
    </field>
    <field>
      <name>dateOfBirth</name>
      <type>java.util.Date</type>
    </field>
    <field>
      <name>aadhaarNumber</name>
      <type>java.lang.String</type>
    </field>
  </queryConfig>
   <queryConfig>
    <className>com.rise.common.model.PersonName</className>
    <component>
      <name>hi</name>
    </component>
    <superClass>
      <name>com.rise.common.model.BaseModel</name>
    </superClass>
    <field>
      <name>title</name>
      <type>java.lang.String</type>
    </field>
    <field>
      <name>firstName</name>
      <type>java.lang.String</type>
    </field>
    <field>
      <name>middleName</name>
      <type>java.lang.String</type>
    </field>
    <field>
      <name>lastName</name>
      <type>java.lang.String</type>
    </field>
    <field>
      <name>suffix</name>
      <type>java.lang.String</type>
    </field>
  </queryConfig>
</queryConfigs>

=== arthurfiddich/rise-app/com.rise.daemon/conf/com.rise.query.config1.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryConfigs xmlns="http://xmlns.rise.com/common/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.rise.com/common/v1 ../xsd/com.rise.query.config.xsd ">
  <queryConfig>
    <className>token</className>
    <component>
      <name>token</name>
    </component>
    <superClass>
      <name>token</name>
    </superClass>
    <field>
      <name>token</name>
      <type>token</type>
    </field>
  </queryConfig>
</queryConfigs>
